version: "3.9" # optional since v1.27.0
services:
  coordinator:
    build:
      context: ./coordinator
    ports:
      - 3000:3000
    environment:
      - "BROKERS=broker-01:3001,broker-02:3001,broker-03:3001"
    volumes:
      - ./coordinator:/opt/coordinator/

  "broker-01":
    build:
      context: ./participant
    hostname: broker-01
    ports:
      - 4001:3001
    volumes:
      - ./participant:/opt/participant/
      - ./_ephemeral/data/01:/opt/participant/data
      - ./_ephemeral/intermediate/01:/opt/participant/intermediate

  "broker-02":
    build:
      context: ./participant
    hostname: broker-02
    ports:
      - 4002:3001
    volumes:
      - ./participant:/opt/participant/
      - ./_ephemeral/data/02:/opt/participant/data
      - ./_ephemeral/intermediate/02:/opt/participant/intermediate

  "broker-03":
    build:
      context: ./participant
    hostname: broker-03
    ports:
      - 4003:3001
    volumes:
      - ./participant:/opt/participant/
      - ./_ephemeral/data/03:/opt/participant/data
      - ./_ephemeral/intermediate/03:/opt/participant/intermediate
