version: "3.9" # optional since v1.27.0
services:
  # precisa que a porta 3000 do container esteja mapeada com alguma porta do host
  # assim podemos acessar o serviço a partir diretamente do terminal do host
  coordinator:
    build:
      context: ./coordinator
    ports:
      - 3000:3000
    environment:
      - "BROKERS=broker-01:3001,broker-02:3001,broker-03:3001"
    volumes:
      - ./coordinator:/opt/coordinator/

  # não precisa de nenhuma porta mapeada com o host, já é acessível a partir do coordenador
  "broker-01":
    build:
      context: ./participant
    hostname: broker-01
    volumes:
      - ./participant:/opt/participant/
      - ./.ephemeral/data/01:/opt/participant/data
      - ./.ephemeral/intermediate/01:/opt/participant/intermediate

  # não precisa de nenhuma porta mapeada com o host, já é acessível a partir do coordenador
  "broker-02":
    build:
      context: ./participant
    hostname: broker-02
    volumes:
      - ./participant:/opt/participant/
      - ./.ephemeral/data/02:/opt/participant/data
      - ./.ephemeral/intermediate/02:/opt/participant/intermediate

  # não precisa de nenhuma porta mapeada com o host, já é acessível a partir do coordenador
  "broker-03":
    build:
      context: ./participant
    hostname: broker-03
    volumes:
      - ./participant:/opt/participant/
      - ./.ephemeral/data/03:/opt/participant/data
      - ./.ephemeral/intermediate/03:/opt/participant/intermediate
